getsaf/shallow-render

- README.md
- lib/examples/using-replacement-modules.spec.ts
- lib/models/test-setup.ts
- lib/shallow.spec.ts
- lib/shallow.ts
- lib/tools/mock-module.ts
Fixes #19 
From the docs:
Angular has a pattern in which they provide full-module replacements specifically designed for testing (see: [HttpClientTestingModule](https://angular.io/api/common/http/testing/HttpClientTestingModule)). These testing modules can be used in your Shallow tests by replacing the original module with the test module.
```typescript
shallow.replaceModule(HttpClientModule, HttpClientTestingModule);
```
If you would like to do this globally, you can use `alwaysReplaceModule` in your global test setup.
```typescript
Shallow.alwaysReplaceModule(HttpClientModule, HttpClientTestingModule);
```
> feat: Allow module replacement

- lib/examples/using-no-template-render.spec.ts
- lib/models/renderer.spec.ts
- lib/models/renderer.ts
- lib/shallow.spec.ts
- lib/shallow.ts
Two new features here:
* Allows rendering without specifying the HTML template while also binding directly to the component properties. Thanks for the idea @ike18t!
* Automatically spy on `@Output` `EventEmitters`
Example:
```typescript
@Component({
selector: 'my-component',
template: '<span (click)="clickName.emit(name)">{{name}}</span>'
})
class MyComponent {
@Input() name: string;
@Output() clickName = new EventEmitter<string>();
}
```
```typescript
it('can bind directly to inputs', async () => {
const {find} = await shallow.render({bind: {name: 'FOO'}});
expect(find('label').nativeElement.textContent).toBe('FOO');
});
it('automatically spys on @Outputs', async () => {
const {find, instance} = await shallow.render({bind: {name: 'BAR'}});
find('label').click(); …
```
> feat: Allow binding directly to component @Input properties

- lib/tools/mock-provider.spec.ts
- lib/tools/mock-provider.ts
There was a bug that would prevent `dontMock` and `neverMock` from skipping mocks for providers in a `forRoot` array unless you used the exact same array reference in your `dontMock` call.
For example:
```typescript
@NgModule()
class MyModule {
static forRoot(): NgModuleWithProviders {
return {
ngModule: MyModule,
providers: [FooService, BarService]
}
}
```
Mocking the `forRoot` providers like this, would not work because each call to `forRoot` yields a new array reference.
```typescript
shallow.dontMock(MyModule.forRoot().providers);
```
This fixes that bug so it works now.
> fix: Make dontMock work provider arrays

- lib/examples/mocking-static-methods.spec.ts
- lib/models/renderer.spec.ts
- lib/models/renderer.ts
- lib/models/test-setup.ts
- lib/shallow.spec.ts
- lib/shallow.ts
Support for mocking static methods:
```typescript
class MyClass {
static reverse(thing: string) {
return thing.split('').reverse();
}
}
```
can be mocked with:
```typescript
shallow.mockStatic(MyClass, {reverse: () => 'mock reverse'});
```
Regular objects can be mocked in this manner too:
```typescript
const FOO = {
bar: () => 'bar'
};
```
Can be mocked with:
```typescript
shallow.mockStatic(FOO, {bar: () => 'mocked bar'});
```
Due to Jasmine spy limitations, **only methods are supported**. If you try to mock a non-method property, an error is thrown. When we begin supporting other test frameworks this limitation may go away (or only exist when using Jasmine).
```typescript
class MyClass {
static foo = 'FOO'
}
```
If you try to mock non-method property `MyClass.foo` will throw an error: …
> feat: Support mocking static functions

- lib/examples/module-with-providers.spec.ts
- lib/shallow.ts
Sometimes, you may want to test your component's module uses the `forRoot` pattern. Previously, you would have to manually `.provide()` any service dependencies when your module used the `forRoot` pattern but with this fix, you can use the `forRoot` output directly in the `Shallow` constructor:
```typescript
@NgModule({
declarations: [MyComponent]
})
class MyModule {
static forRoot(): ModuleWithProviders {
return {
ngModule: MyModule,
providers: [MyService],
}
}
```
```typescript
shallow = new Shallow(MyComponent, MyModule)
.provide(MyService);
```
```typescript
shallow = new Shallow(MyComponent, MyModule.forRoot());
```
> feat: Support ModuleWithProviders in Shallow constructor

- lib/examples/component-with-routing.spec.ts
- lib/examples/structural-directive.spec.ts
- lib/models/renderer.spec.ts
- lib/models/renderer.ts
- lib/models/rendering.spec.ts
- lib/models/rendering.ts
Support for testing Structural Directives:
Fixes #47 
The general idea here is that when testing structural directives, you may simply test for the existence (or not) of the `Rendering#element` property. 
Positive test case (just what you'd expect):
```typescript
it('shows content when value is "foo"', async () => {
const {element} = await shallow.render(`<div *showIfFoo="'foo'">Show Me</div>`);
expect(element.nativeElement.textContent).toBe('Show Me');
/* -- or simply -- */
expect(element).toBeDefined();
});
```
Negative test case:
```typescript
it('does not show content when value is not "foo"', async () => {
const {element} = await shallow.render(`<div *showIfFoo="'bar'">Show Me</div>`);
expect(element).not.toBeDefined();
});
```
> feat: Support testing structural directives

- lib/examples/component-with-content-child.spec.ts
- lib/examples/template-with-hash-references.spec.ts
- lib/tools/ng-mock.spec.ts
- lib/tools/ng-mock.ts
Addresses #52 
When a component is written using the template-hash pattern, we sometimes need to mock methods on these components when we use them. For example:
in `MyComponent` we may render something like this:
```xml
<list-container #container>
<list-item (click)="container.collapse()">Collapse the parent!</list-item>
</list-container>
```
Shallow will provide us a mock of `list-container` and `list-item`, but if we want to write a test that ensures we hooked up the `click` handler correctly, we'll have to call the `collapse` method on the `list-container` component so we'll need to mock that method out. Before this change, Shallow would not apply mock properties to component instances but now we can.
```typescript
const {find} = await shallow
.mock(ListContainerComponent, {collapse: …
```
> feat: Allow mocking component instance properties

- lib/tools/ng-mock.spec.ts
- lib/tools/ng-mock.ts
> fix: Allow mocking of components with empty selectors

- lib/examples/using-always-import.spec.ts
- lib/models/test-setup.ts
- lib/shallow.spec.ts
- lib/shallow.ts
- lib/tools/copy-test-module.ts
Suggested in #59, there are good uses for providing a way to add module imports to an existing module.
This can now be done simply by using `.import(ModuleToImport)`:
```typescript
beforeEach(() => {
shallow = new Shallow(MyComponent, ComponentModule).import(BrowserAnimationsModule);
});
```
Or, if you want to import it for all specs globally:
```typescript
Shallow.alwaysImport(BrowserAnimationsModule);
```
Thanks @kylecannon for helping iron out the use case for this.
> feat: Add support for `Shallow#import` and `Shallow.alwaysImport`

- lib/examples/component-with-routing.spec.ts
- lib/tools/mock-module.spec.ts
- lib/tools/mock-module.ts
Address some difficulties with mocking modules from #60 
I think with this change, mocking the RouterModule will be much easier and intuitive.
```typescript
shallow.replaceModule(RouterModule, RouterTestingModule.withRoutes(testRoutes));
```
> fix: Match replacementModules on ModuleWithProviders#ngModule

- lib/examples/component-with-content-child.spec.ts
- lib/tools/ng-mock.ts
- package-lock.json
- package.json
Fix for #81 and various other issues involving mocking of the Angular `RouterModule`.
> fix: Fix error when trying to mock the RouterModule

- build-with-supported-angluars.js
- lib/examples/using-no-template-render.spec.ts
- lib/models/rendering.spec.ts
- lib/models/rendering.ts
- lib/tools/output-proxy.spec.ts
- lib/tools/output-proxy.ts
Now, instead of:
Shallow#render now returns an `outputs` object. The outputs object only allows referencing the EventEmitter properties of the test component that have been marked with `@Output`.
```typescript
it('emits "FOO" on button click', async () => {
const {find, instance} = await shallow.render();
find('button').triggerEventHandler('click', null);
expect(instance.mySelectOutput.emit)
.toHaveBeenCalledWith('FOO');
});
```
We can avoid the use of the component instance like this:
```typescript
it('emits "FOO" on button click', async () => {
const {find, outputs} = await shallow.render();
find('button').triggerEventHandler('click', null);
expect(outputs.mySelectOutput.emit)
.toHaveBeenCalledWith('FOO');
});
```
-- or, if you want to get weird with it --
```typescript
it('emits "FOO" …
```
> feat: Allow expectations on an `outputs` object instead of instance

- lib/models/renderer.spec.ts
- lib/models/renderer.ts
Should fix https://github.com/getsaf/shallow-render/issues/105
~~Draft~~ PR to showcase the idea, code style and test is debatable
> Components without selectors will have a default one assigned

- package-lock.json
- package.json
There's a breaking change in ng-mocks 7.5.x that we want to avoid.
> chore: Keep up-to-date with ng-mocks

- lib/models/angular-module.ts
- lib/tools/mock-module.spec.ts
- lib/tools/mock-module.ts
- lib/tools/type-checkers.ts
Fix for #108 
Using `replaceModule` had a side-effect of potentially replacing an "exported" module with a `ModuleWithProviders` which is explicitly not supported in Angular modules. All Angular module exports *must* be classes with the `NgModule` decorator applied.
This
```typescript
Shallow.alwaysReplaceModule(RouterModule, RouterTestingModule.withRoutes(...));
```
Would cause an issue when a module under test was exporting the RouterModule like so:
```typescript
@NgModule({exports: [RouterModule]})
class MyModule {}
```
What happened was, `MyModule` was having it's export replaced with the `ModuleWithProviders` produced by the `RouterTestingModule` and TestBed would choke when parsing the test module.
The solution is to extract the `ngModule` out of the `moduleWithProviders` when it …
> fix: Do not use moduleWithProviders in mock-module exports

- lib/examples/component-with-ng-component-outlet.spec.ts
- lib/models/renderer.spec.ts
- lib/models/test-setup.ts
- lib/shallow.spec.ts
- lib/shallow.ts
- lib/tools/copy-test-module.ts
Should fix issue #117. Turns out that using EntryComponents in TestBed is [pretty tough](https://github.com/angular/angular/issues/12079) but we are able to swallow all that complexity in shallow-render so there's no special handling on the user's end!
Thanks @nbcormier for reporting!
Quick notes:
When rendering "normal" components, Angular looks for "selectors" in the template and searches in the module-tree for a component that matches the selector. In testing, we have total control over the module so we can swap out dummy components to match up with selectors and our tests are happy.
EntryComponents bypass this and are referenced directly by their class object instead of being plucked out of the module by their selectors. This can make components that render EntryComponents hard to …
> fix: Allow entry-components in TestModules

- lib/test-frameworks/shallow-matchers.ts
- lib/test-frameworks/types.ts
Custom Matchers weren't working when writing tests with Jest.
> fix: Fix jest matchers

- lib/shallow.spec.ts
- lib/shallow.ts
provideMock combines provide() and neverMock() for allowing the
developer to provide his/her own mock instead of relying on
shallow-render.
> feat: Add provideMock

- lib/examples/component-with-provided-in-root.spec.ts
- lib/models/mock-of-provider.ts
- lib/models/renderer.ts
- lib/tools/mock-provider.ts
- lib/tools/ng-mock.ts
fix #128
Taking @apastuhov's suggestion and simply using `TestBed.overrideProvider`. Sorry it took so long to realize this was, indeed, the simplest way forward.
Unfortunately, this approach will *not* auto-mock root providers, they must specify some sort of mock with `shallow.mock` for them to take effect.
> fix: Use TestBed.overrideProvider to support rootProviders

- lib/examples/component-with-forms.spec.ts
- lib/shallow.ts
- package.json
Trying to use mocks of the FormsModule or ReactiveForms module is pretty-much pointless. The only solution to this is to *manually* add `Shallow.neverMock(FormsModule, ReactiveFormsModule)` into your test setup. I believe everyone who uses forms must do this so I just do it by default now in shallow.
Same for `HAMMER_GESTURE_CONFIG`.
> feat: Do not mock certain core Angular things by default

- lib/examples/component-with-structural-directive.spec.ts
- lib/models/rendering.spec.ts
- lib/models/rendering.ts
- lib/models/test-setup.ts
- lib/shallow.spec.ts
- lib/shallow.ts
- lib/tools/ng-mock.spec.ts
- lib/tools/ng-mock.ts
New features:
```typescript
const greenFoo = findComponent(FooComponent, {query: '.green'})
```
```typescript
const {findStructuralDirective} = await shallow.render();
const fooDirective = findStructuralDirective(FooDirective);
```
-- or -- with a predicate
```typescript
const {findStructuralDirective} = await shallow.render();
const fooDirective = findStructuralDirective(FooDirective, fd => fd.directiveProperty === 'cool');
```
```typescript
const {renderStructuralDirective} = await shallow.render();
renderStructuralDirective(FooDirective);
// Un-render with a second argument
renderStructuralDirective(FooDirective, false);
```
-- or -- render specific instances of a directive
```typescript
const {findStructuralDirective, renderStructuralDirective} = await shallow.render();
const …
```
> feat: Allow rendering of structural directives

- lib/examples/component-with-input.spec.ts
- lib/examples/component-with-output.spec.ts
- lib/examples/component-with-reactive-input.spec.ts
Hi!
I really liked your project but I found out that simulating some integrations were difficult for me and looking for solution wasn't easy => input html element and @Outputs. I created a couple of examples that illustrate how can you use shallow-render to also test such cases. Hopes that they will be useful!
If you have any ideas about changing code style in proposed examples please let me know.
Cheers,
Mati
> docs: Additional examples for events

- lib/examples/mocking-injection-tokens.spec.ts
- lib/models/renderer.spec.ts
- lib/models/renderer.ts
- lib/models/rendering.spec.ts
- lib/models/rendering.ts
- lib/shallow.ts
- lib/tools/mock-provider.spec.ts
- lib/tools/mock-provider.ts
Addresses deficiencies noted in #153 
This allows mocking injection tokens directly like:
```typescript
const STRING_TOKEN = new InjectionToken<string>('A string injection token');
const FUNCTION_TOKEN = new InjectionToken<() => string>('A function injection token');
// Can now be mocked with:
shallow
.mock(STRING_TOKEN, 'mocked value')
.mock(FUNCTION_TOKEN, () => 'mocked function return');
```
> feat: Allow directly mocking injection tokens

- karma.conf.ts
- lib/models/rendering.spec.ts
- lib/shallow.spec.ts
- lib/shallow.ts
- lib/tools/ng-mock.spec.ts
- lib/tools/ng-mock.ts
- package-lock.json
- tsconfig.json
Addressing #163 
Updating types to match newer versions of ng-mocks.
> feat: Add Shallow.alwaysMockPipe

- lib/examples/component-with-forms.spec.ts
- lib/tools/create-test-module.ts
- lib/tools/mock-provider.spec.ts
- lib/tools/mock-provider.ts
- lib/tools/mock-with-inputs-and-outputs-and-stubs.ts
- lib/tools/ng-mock.ts
BugFix for issue reported in #176.
No new features, just had a regression when mocking providers that caused tests with certain kinds of module structures to overflow the stack!
Realized a few more cleanups along the way.
> fix(176): Fix recursion issues when mocking components

- lib/models/rendering.spec.ts
- lib/tools/mock-provider.spec.ts
- lib/tools/mock-provider.ts
- package-lock.json
Per #185, it seems that passing through values for injection tokens can cause the jest test-runner to report components missing from modules.
This undoes the recent change to pass through injection token values in tests and instead, provide a default mock string value.
Also, bumped local Angular versions to the latest.
> fix: Do not pass-through injection token values

- lib/examples/service-only-testing.spec.ts
- lib/examples/using-replacement-modules.spec.ts
- lib/models/custom-error.spec.ts
- lib/models/query-match.spec.ts
- lib/models/renderer.spec.ts
- lib/models/renderer.ts
- lib/models/rendering.spec.ts
- lib/models/test-setup.spec.ts
- lib/models/test-setup.ts
- lib/shallow.spec.ts
- lib/shallow.ts
- lib/tools/create-service.spec.ts
- lib/tools/create-service.ts
- lib/tools/create-test-module.ts
- lib/tools/inject-root-providers.ts
- lib/tools/mock-component.spec.ts
- lib/tools/mock-directive.spec.ts
- lib/tools/mock-provider.spec.ts
- lib/tools/mock-statics.ts
- lib/tools/ng-mock.spec.ts
- lib/tools/output-proxy.spec.ts
Add native support for service testing: #166 
Can be used like:
```ts
beforeEach(() =>{ 
shallow = new Shallow(MyService, MyModule);
})
it('reverses a string', () => {
const {instance} = shallow.createService();
expect(instance.reverse('foobar')).toBe('raboof');
});
```
> feat: Native support for service testing

- lib/shallow.ts
- lib/tools/mock-component.spec.ts
- lib/tools/mock-component.ts
- lib/tools/mock-directive.spec.ts
- lib/tools/mock-directive.ts
- lib/tools/mock-with-inputs-and-outputs-and-stubs.ts
- lib/tools/ng-mock.ts
Taking a simpler approach to compatibility with Angular Forms components to solve for: #188 
Instead of mocking *all* component providers in hopes of successfully finding/mocking the `NG_VALUE_ACCESSOR`, we will now inject `NG_VALUE_ACCESSOR` into every mock component (whether or not it asks for it).
Pros:
* This should handle every scenario for testing mocked components that are used with `NgValue`
Cons:
* Tests for components that use mocks of components that do not actually provide `NG_VALUE_ACCESSOR` will pass when they should actually fail.
> feat: Manually inject NG_VALUE_ACCESSOR instead of mocking all component providers

- package.json
Thanks a lot for updating shallow-render to work with Angular 14. After the update, when importing `Shallow` like this:
```
import { Shallow } from 'shallow-render';
```
I got the following error:
```
Cannot find module 'shallow-render' from [...]
```
The error occurs because in your most recent commit you changed the `"main"` entry in `package.json` to `"module"`. I was able to work around the error by importing `{ Shallow } from 'shallow-render/dist'` instead, but figured it'd make more sense to re-add the `main` entry in `package.json` again. According to the [package.json docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#main), without a `"main"` entry the import will by default look for the module in the package's root folder.
> Re-add "main" in package.json to fix module resolution when importing shallow-render

- lib/examples/component-with-bindings-defined-in-the-component-directive.spec.ts
- lib/tools/reflect.spec.ts
- lib/tools/reflect.ts
Components or directives may define inputs inside the `@Component` or `@Directive` decorators instead of using `@Input` and `@Output` directives.
This was supported in shallow-render until a recent Angular update required a total refactor of I/O binding parsing which broke support for this pattern.
> fix: Fix usage of inputs/outputs defined in the component directive

- package.json
- tsconfig.json
> fix: Use ES2015 to avoid zonejs issues with Jest

- lib/examples/component-with-bindings.spec.ts
- lib/models/recursive-partial.ts
- lib/tools/reflect.spec.ts
- lib/tools/reflect.ts
This PR addresses the issue outlined in https://github.com/getsaf/shallow-render/issues/255.
**Key Changes**:
Support for **@input()** with InputOption (e.g. Input({required: true}): This change enables shallow-render to handle components that use **@input()** decorated properties with InputOptions, expanding the ability to mock and manipulate inputs in tests.
Support for Input Signals: Input signals are now also supported in the shallow rendering of components, providing further flexibility in simulating and testing input changes.
> Support different input bindings

- lib/examples/component-with-bindings.spec.ts
- lib/models/recursive-partial.ts
- lib/models/renderer.ts
- lib/models/rendering.ts
- lib/tools/create-container.spec.ts
- lib/tools/create-container.ts
- lib/tools/output-proxy.spec.ts
- lib/tools/output-proxy.ts
This PR addresses multiple issues when working with signal inputs and outputs:
- Provides support for [input signals with transform](https://angular.dev/api/core/InputSignalWithTransform)
- Provides support for [output signals](https://angular.dev/api/core/output)
- Provides helper method to overwrite a single input in a test by adding `updateBinding` on `ProxyShallowContainerComponent `
Please also backport this change to angular 18 .
> Improve signal handling
